name: Deploy API image to Amazon ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  API_ECR_REPOSITORY: fastfood-fiap

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'microsoft'

  build:
    name: Build API
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Install maven
        run: |
          if ! command -v mvn &> /dev/null
          then
              echo "Maven not found, installing..."
              sudo apt-get update
              sudo apt-get install -y maven
          else
              echo "Maven is already installed"
          fi

      - name: Build with Maven
        run: mvn clean install -Dmaven.test.failure.ignore=true

  deploy:
    name: Deploy Image API to ECR
    runs-on: ubuntu-latest
    needs: build
    env:
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #AWS_SESSION_TOKEN:
      IMAGE_TAG: latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY && aws configure set region $AWS_REGION

      - name: Login to Amazon ECR
        run: echo $AWS_SECRET_ACCESS_KEY | AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY

      - name: Build Docker image
        run: docker build -t $ECR_REGISTRY/$API_ECR_REPOSITORY:$IMAGE_TAG .

      - name: Push Docker image to ECR
        run: docker push $ECR_REGISTRY/$API_ECR_REPOSITORY:$IMAGE_TAG
